version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 8000:8000
      - 9443:9443
    pull_policy: always
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.portainer:/data
