# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[aws]
disabled = true

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = '󰠅 '
style = 'blue bold'

# Replace the "❯" symbol in the prompt with "∫"
[character]
success_symbol = "[∫](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[docker_context]
disabled = true

[gradle]
disabled = true

[hostname]
ssh_only = true
format = "ssh on [$hostname](bold red) at "

[java]
disabled = true

[kubernetes]
disabled = true

[nodejs]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
